/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package excarbol_4;
import arbol.Arbol;

public class ArbolBinario extends javax.swing.JFrame {
   
    Arbol arbolito;
    
    public ArbolBinario() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtfN1 = new javax.swing.JTextField();
        jtfN2 = new javax.swing.JTextField();
        jtfN3 = new javax.swing.JTextField();
        jtfN4 = new javax.swing.JTextField();
        jtfN5 = new javax.swing.JTextField();
        jtfN6 = new javax.swing.JTextField();
        jtfN7 = new javax.swing.JTextField();
        jtfN8 = new javax.swing.JTextField();
        jtfN9 = new javax.swing.JTextField();
        jtfN10 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnConstruir = new javax.swing.JButton();
        btnPre = new javax.swing.JButton();
        btnIn = new javax.swing.JButton();
        btnPost = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 51, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Arbol Binario");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(406, 406, 406)
                .addComponent(jLabel1)
                .addContainerGap(430, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        jPanel1.add(jtfN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 100, 70, 30));
        jPanel1.add(jtfN2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 70, 40));
        jPanel1.add(jtfN3, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 310, 60, 40));

        jtfN4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfN4ActionPerformed(evt);
            }
        });
        jPanel1.add(jtfN4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, 80, 40));
        jPanel1.add(jtfN5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, 80, 40));
        jPanel1.add(jtfN6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 420, 80, 40));
        jPanel1.add(jtfN7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 430, 80, 40));
        jPanel1.add(jtfN8, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 430, 80, 40));

        jtfN9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfN9ActionPerformed(evt);
            }
        });
        jPanel1.add(jtfN9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 540, 80, 40));
        jPanel1.add(jtfN10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 540, 80, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\Escuela\\7mo\\LyAII\\U1\\Arbol_binario_4.PNG")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 630, 670, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Expresion");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 80, 150, 50));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("R((6^2)-2+(3^2))");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 140, -1, -1));

        btnConstruir.setText("Construir Arbol");
        btnConstruir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConstruirActionPerformed(evt);
            }
        });
        jPanel1.add(btnConstruir, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 460, 130, 50));

        btnPre.setText("PreOrden");
        btnPre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreActionPerformed(evt);
            }
        });
        jPanel1.add(btnPre, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 190, 130, 50));

        btnIn.setText("InOrden");
        btnIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInActionPerformed(evt);
            }
        });
        jPanel1.add(btnIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 270, 130, 50));

        btnPost.setText("PostOrden");
        btnPost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPostActionPerformed(evt);
            }
        });
        jPanel1.add(btnPost, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 360, 130, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 756, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfN4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfN4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfN4ActionPerformed

    private void jtfN9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfN9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfN9ActionPerformed

    private void btnPostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPostActionPerformed
        cargarArbol();
        jTextArea1.setText(arbolito.posOrden(arbolito.getRaiz()));
    }//GEN-LAST:event_btnPostActionPerformed

    private void btnConstruirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConstruirActionPerformed
        jtfN1.setText("RAIZ");
        jtfN2.setText("+");
        jtfN3.setText("-");
        jtfN4.setText("^");
        jtfN5.setText("^");
        jtfN6.setText("2");
        jtfN7.setText("3");
        jtfN8.setText("2");
        jtfN9.setText("6");
        jtfN10.setText("2");
        
    }//GEN-LAST:event_btnConstruirActionPerformed

    private void btnPreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreActionPerformed
        cargarArbol();
        jTextArea1.setText(arbolito.preOrden(arbolito.getRaiz()));
    }//GEN-LAST:event_btnPreActionPerformed

    private void btnInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInActionPerformed
        cargarArbol();
        jTextArea1.setText(arbolito.inOrden(arbolito.getRaiz()));
    }//GEN-LAST:event_btnInActionPerformed

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ArbolBinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ArbolBinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ArbolBinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ArbolBinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ArbolBinario().setVisible(true);
            }
        });
    }
    
    public void cargarArbol(){
//        arbolito = new Arbol(jtfN1.getText());//Raiz
        arbolito = new Arbol(jtfN2.getText());
        
        //Nivel1
//        arbolito.insertIzquierda(jtfN2.getText(), arbolito.getRaiz());// "+"
        arbolito.insertIzquierda(jtfN3.getText(), arbolito.getRaiz());// "-"
        arbolito.insertarDerecha(jtfN4.getText(), arbolito.getRaiz());// "^"
        
//        //Nivel2
        arbolito.insertIzquierda(jtfN3.getText(), arbolito.getRaiz().getIzquierda());// "-"
        arbolito.insertarDerecha(jtfN4.getText(), arbolito.getRaiz().getDerecha());// "^"
//        
//        //Nivel3
        arbolito.insertIzquierda(jtfN5.getText(), arbolito.getRaiz().getIzquierda());// "^"
        arbolito.insertarDerecha(jtfN6.getText(), arbolito.getRaiz().getIzquierda());// "2"
        arbolito.insertIzquierda(jtfN7.getText(), arbolito.getRaiz().getDerecha());// "3"
        arbolito.insertarDerecha(jtfN8.getText(), arbolito.getRaiz().getDerecha());// "2"
////        
//        //Nivel4
        arbolito.insertIzquierda(jtfN9.getText(), arbolito.getRaiz().getIzquierda().getIzquierda()); // "6"
        arbolito.insertarDerecha(jtfN10.getText(), arbolito.getRaiz().getIzquierda().getIzquierda());// "2"
//        

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConstruir;
    private javax.swing.JButton btnIn;
    private javax.swing.JButton btnPost;
    private javax.swing.JButton btnPre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jtfN1;
    private javax.swing.JTextField jtfN10;
    private javax.swing.JTextField jtfN2;
    private javax.swing.JTextField jtfN3;
    private javax.swing.JTextField jtfN4;
    private javax.swing.JTextField jtfN5;
    private javax.swing.JTextField jtfN6;
    private javax.swing.JTextField jtfN7;
    private javax.swing.JTextField jtfN8;
    private javax.swing.JTextField jtfN9;
    // End of variables declaration//GEN-END:variables
}
